/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AkceRouteImport } from './routes/akce'
import { Route as CoChcemeRouteImport } from './routes/co-chceme'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as Volby2026RouteImport } from './routes/volby-2026'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AkceRoute = AkceRouteImport.update({
  id: '/akce',
  path: '/akce',
  getParentRoute: () => rootRouteImport,
} as any)
const CoChcemeRoute = CoChcemeRouteImport.update({
  id: '/co-chceme',
  path: '/co-chceme',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const Volby2026Route = Volby2026RouteImport.update({
  id: '/volby-2026',
  path: '/volby-2026',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/akce': typeof AkceRoute
  '/co-chceme': typeof CoChcemeRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/volby-2026': typeof Volby2026Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/akce': typeof AkceRoute
  '/co-chceme': typeof CoChcemeRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/volby-2026': typeof Volby2026Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/akce': typeof AkceRoute
  '/co-chceme': typeof CoChcemeRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/volby-2026': typeof Volby2026Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/akce' | '/co-chceme' | '/kontakt' | '/o-nas' | '/volby-2026'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/akce' | '/co-chceme' | '/kontakt' | '/o-nas' | '/volby-2026'
  id:
    | '__root__'
    | '/'
    | '/akce'
    | '/co-chceme'
    | '/kontakt'
    | '/o-nas'
    | '/volby-2026'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AkceRoute: typeof AkceRoute
  CoChcemeRoute: typeof CoChcemeRoute
  KontaktRoute: typeof KontaktRoute
  ONasRoute: typeof ONasRoute
  Volby2026Route: typeof Volby2026Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akce': {
      id: '/akce'
      path: '/akce'
      fullPath: '/akce'
      preLoaderRoute: typeof AkceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/co-chceme': {
      id: '/co-chceme'
      path: '/co-chceme'
      fullPath: '/co-chceme'
      preLoaderRoute: typeof CoChcemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volby-2026': {
      id: '/volby-2026'
      path: '/volby-2026'
      fullPath: '/volby-2026'
      preLoaderRoute: typeof Volby2026RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AkceRoute: AkceRoute,
  CoChcemeRoute: CoChcemeRoute,
  KontaktRoute: KontaktRoute,
  ONasRoute: ONasRoute,
  Volby2026Route: Volby2026Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
